Integration of Boarding control component
owels45/Airport pull request #16
Opened 2018-01-30 16:55 UTC by mortenterhart

2018-01-30 17:04 UTC, patrick246 requested changes
Compiliert nicht, da die POM auf Java 5 gestellt ist. Mit folgendem Code lässt sicht Java 8 einstellen
```
<build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

2018-01-30 17:12 UTC, mortenterhart commented
`pom.xml` ist nun auf 1.8 eingestellt

2018-01-30 17:17 UTC, patrick246 requested changes
Nicht die pom von der component ist das Problem, sondern die von der main-application. Kannst du das bitte noch ändern? Kann Maven bei dir einmal komplett durchlaufen (und zwar das airport-Projekt)?

2018-01-30 17:25 UTC, patrick246 commented
Es gibt Konflikte, bitte einmal resolven

2018-01-30 17:26 UTC, mortenterhart commented
Habs gesehen, Konflikte sind gelöst

2018-01-30 17:28 UTC, patrick246 commented
In deinem Branch fehlt die Klasse CheckInDeskReceipt, die aber im aktuellen master vorhanden ist. Deshalb compiliert es nicht

2018-02-06 08:36 UTC, mortenterhart commented
Boarding Control kann gemergt werden, bitte kurz Review machen

2018-02-07 15:27 UTC, filipe96 approved these changes
👨🏻‍💻👍

2018-02-15 13:17 UTC, closed without merging